### ISSUE TITLE
Docker Nginx not working

### ISSUE THREAD

**Issue by sajal09** [mc-internship/covid19visualizer#10]
Starting covid19visualizer_backend_1  ... done
Starting covid19visualizer_frontend_1 ... done
Starting covid19visualizer_nginx_1    ... error

ERROR: for covid19visualizer_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint covid19visualizer_nginx_1 (00b55a2f304113f6fd37d7d75b0c04012392e3992f917a15bab2438c34c5dad1): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint covid19visualizer_nginx_1 (00b55a2f304113f6fd37d7d75b0c04012392e3992f917a15bab2438c34c5dad1): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by yugeshk** [comment]
Something is already running on port 80 as per the logs. Just kill that process. For linux : `fuser -k 80/tcp`
