### ISSUE TITLE
 Microsoft ODBC driver needed in machine to connect Django to AzureSql 

### ISSUE THREAD

**Issue by sajal09** [mc-internship/covid19visualizer#15]
I had to install Microsoft ODBC driver in ubuntu to connect to azuresql from django. All other dependencies needed can be installed using pip (I have added them in requirements.txt file in backendapi branch) but this driver needs to be present in the ubuntu system.
Relevant links (second one received from Yugesh):
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15
https://medium.com/@__pamaron__/deploy-a-django-application-connected-to-azure-sql-using-docker-and-azure-app-service-a2c107773c11

**Comment by yugeshk** [comment]
Please give instructions for installing them on `ubuntu` we can add it to the `Dockerfile`

**Comment by yugeshk** [comment]
Need to add this to the Heroku docker as well.
